name: phone_java
description: "关怀模式 AI 助手 Flutter 项目"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  dio_http2_adapter: ^2.7.0
  flutter_dotenv: ^6.0.0
  flutter_phone_direct_caller: ^2.2.1
  flutter_tts: ^4.2.5
  fluwx: ^5.7.5
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  record: ^6.2.0
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  avatar_glow: ^3.0.1
  shared_preferences: ^2.3.2
  audioplayers: ^6.6.0
  intl: ^0.20.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
