name: phone_java
description: "关怀模式 AI 助手 Flutter 项目"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4  # 用于简易唤起前置相机拍照


  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  dio_http2_adapter: ^2.7.0
  flutter_dotenv: ^6.0.0
  flutter_phone_direct_caller: ^2.2.1
  flutter_tts: ^4.2.5
  fluwx: ^5.7.5
  path_provider: ^2.1.5
  record: ^6.2.0
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  avatar_glow: ^3.0.1
  shared_preferences: ^2.3.2
  audioplayers: ^6.6.0
  intl: ^0.20.2
  #  直接强制写明最新版本号
  flutter_baidu_mapapi_base: 3.9.9+1
  flutter_baidu_mapapi_map: 3.9.9+1
  flutter_baidu_mapapi_search: 3.9.9+1
  flutter_baidu_mapapi_utils: 3.9.9+1
  flutter_bmflocation: 3.8.4
  permission_handler: ^12.0.1
  battery_plus: ^7.0.0      # 获取电量
  volume_controller: ^2.0.8  # 获取音量

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
  # 如果想让 Android 图标支持自适应（背景和前景分离）
  adaptive_icon_background: "#FFFFFF" # 背景色
  adaptive_icon_foreground: "assets/appicon.png" # 前景图